= rust 生成exe的方法

安装 rust
https://www.rust-lang.org/zh-CN/learn/get-started
在终端窗口进入 main/rust/ 目录。

== rust 版本

需要使用 rustc 1.61.0 版本，更好的版本会导致无法启动 javaw.exe 程序。

* 安装命令：

```
rustup install 1.61.0
# 然后让 rust 切换到该版本
rustup default 1.61.0
```

* 产生异常:

```
error: package `cc v1.1.22` cannot be built because it requires rustc 1.63 or newer, while the currently active rustc version is 1.61.0

```
* cc模块需要升级rust到1.63
* 升级rust1.6.3

```
rustup install 1.63.0
rustup default 1.63.0
```

* 检查版本

```
rustc --version
```

接下来就可以用 cargo 命令进行编译了。

因为 rustc > 1.61.0 会导致无法启动 javaw.exe，报告下列错误：

```
Error occurred during initialization of VM
java/lang/NoClassDefFoundError: java/lang/Object
```

具体原因不明。

== 修改Cargo.toml其中软件名和作者

==  输入命令

cargo build --release

== 可能遇到的问题

=== 1.网络问题

解决方法：

编辑你的 ~/.cargo/config 文件（没有的话就创建一个）

放到 `$HOME/.cargo/config``` 文件中``

将以下程序写入

==== [source.crates-io]

registry = "https://github.com/rust-lang/crates.io-index"

replace-with = 'ustc'

==== [source.ustc]

registry = "git://mirrors.ustc.edu.cn/crates.io-index"

== jvm.json 中的模块

启动时报告下面的错误：

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 59 common frames omitted
Caused by: java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
        at com.baomidou.mybatisplus.core.toolkit.Sequence.getMaxWorkerId(Sequence.java:106)
```

这是因为 mybatis 依赖了 java.lang.management 包，需要在制作 java image 时包含这个包。

制作 jre image 的命令如下：

```cmd
set PATH_TO_FX_MODS=c:\java\javafx\javafx-jmods-17.0.2\
set JAVA_HOME=c:\java\openjdk-16.0.1
set JAVA_MODULES=java.naming,java.sql,jdk.crypto.cryptoki,java.management,
SET JAVAFX_MODULES=javafx.controls,javafx.fxml

rmdir jrefx /q /s

%JAVA_HOME%\bin\jlink --module-path %PATH_TO_FX_MODS% ^
    --add-modules %JAVA_MODULES%%JAVAFX_MODULES% ^
    --strip-debug --compress 2 --no-header-files --no-man-pages ^
	--output jrefx
```




