server:
  port: 8082

spring:
  ## 数据库配置
  datasource:
    url: jdbc:sqlite:.\data\database.db3
    username:
    password:
    driver-class-name: org.sqlite.JDBC

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    type-aliases-package: com.app.pojo
    mapper-locations: classpath:com.app.mapper.xml/*.xml

  main:
    allow-bean-definition-overriding: true